import {
  CellInterface,
  CellRotation,
  CellType,
  PropertyColor,
  SpecialType,
} from '../types';

export const cells: CellInterface[] = [
  {
    type: CellType.JAIL,
    id: 10,
    color: PropertyColor.NONE,
    rotation: CellRotation.UP,
    position: {
      xStart: 1,
      yStart: 1,
      xEnd: 2,
      yEnd: 2,
    },
  },
  {
    type: CellType.PROPERTY,
    id: 11,
    price: 91,
    levelInfo: {
      level: 0,
      label: 'level',
      rent: [101, 121, 143, 166, 190],
    },
    title: 'The Angel Islington',
    color: PropertyColor.PURPLE,
    rotation: CellRotation.UP,
    position: {
      xStart: 2,
      yStart: 1,
      xEnd: 3,
      yEnd: 2,
    },
  },
  {
    type: CellType.SPECIAL_PROPERTY,
    id: 12,
    price: 1204,
    levelInfo: {
      level: 0,
      label: 'level',
      rent: [1304, 1524, 1754, 1994, 2244],
    },
    specialType: SpecialType.WATER,
    color: PropertyColor.NONE,
    rotation: CellRotation.UP,
    position: {
      xStart: 3,
      yStart: 1,
      xEnd: 4,
      yEnd: 2,
    },
  },
  {
    type: CellType.PROPERTY,
    id: 13,
    price: 97,
    levelInfo: {
      level: 0,
      label: 'level',
      rent: [107, 127, 149, 172, 196],
    },
    title: 'Trafalgar Square',
    color: PropertyColor.PURPLE,
    rotation: CellRotation.UP,
    position: {
      xStart: 4,
      yStart: 1,
      xEnd: 5,
      yEnd: 2,
    },
  },
  {
    type: CellType.PROPERTY,
    id: 14,
    price: 112,
    levelInfo: {
      level: 0,
      label: 'level',
      rent: [122, 144, 168, 194, 220],
    },
    title: 'Northumberland Avenue',
    color: PropertyColor.PURPLE,
    rotation: CellRotation.UP,
    position: {
      xStart: 5,
      yStart: 1,
      xEnd: 6,
      yEnd: 2,
    },
  },
  {
    type: CellType.TRAIN_STATION,
    id: 15,
    price: 700,
    levelInfo: {
      level: 0,
      label: 'station',
      rent: [800, 1000, 1200, 1400],
    },
    title: 'Fenchurch St. Station',
    color: PropertyColor.NONE,
    rotation: CellRotation.UP,
    position: {
      xStart: 6,
      yStart: 1,
      xEnd: 7,
      yEnd: 2,
    },
  },
  {
    type: CellType.PROPERTY,
    id: 16,
    price: 125,
    levelInfo: {
      level: 0,
      label: 'level',
      rent: [136, 160, 186, 212, 240],
    },
    title: 'Marlborough Street',
    color: PropertyColor.ORANGE,
    rotation: CellRotation.UP,
    position: {
      xStart: 7,
      yStart: 1,
      xEnd: 8,
      yEnd: 2,
    },
  },
  {
    type: CellType.COMMUNITY_CHEST,
    id: 17,
    color: PropertyColor.NONE,
    rotation: CellRotation.UP,
    position: {
      xStart: 8,
      yStart: 1,
      xEnd: 9,
      yEnd: 2,
    },
  },
  {
    type: CellType.PROPERTY,
    id: 18,
    price: 148,
    levelInfo: {
      level: 0,
      label: 'level',
      rent: [170, 196, 224, 254, 286],
    },
    title: 'Fleet Street',
    color: PropertyColor.ORANGE,
    rotation: CellRotation.UP,
    position: {
      xStart: 9,
      yStart: 1,
      xEnd: 10,
      yEnd: 2,
    },
  },
  {
    type: CellType.PROPERTY,
    id: 19,
    price: 208,
    levelInfo: {
      level: 0,
      label: 'level',
      rent: [232, 260, 290, 320, 352],
    },
    title: 'Old Kent Road',
    color: PropertyColor.ORANGE,
    rotation: CellRotation.UP,
    position: {
      xStart: 10,
      yStart: 1,
      xEnd: 11,
      yEnd: 2,
    },
  },
  {
    type: CellType.FREE_PARKING,
    id: 20,
    color: PropertyColor.NONE,
    rotation: CellRotation.UP,
    position: {
      xStart: 11,
      yStart: 1,
      xEnd: 12,
      yEnd: 2,
    },
  },
  {
    type: CellType.PROPERTY,
    id: 9,
    price: 81,
    levelInfo: {
      level: 0,
      label: 'level',
      rent: [93, 110, 128, 148, 170],
    },
    title: 'Whitechapel Road',
    color: PropertyColor.LIGHT_BLUE,
    rotation: CellRotation.LEFT,
    position: {
      xStart: 1,
      yStart: 2,
      xEnd: 2,
      yEnd: 3,
    },
  },
  {
    type: CellType.PROPERTY,
    id: 21,
    price: 211,
    levelInfo: {
      level: 0,
      label: 'level',
      rent: [235, 265, 297, 330, 364],
    },
    title: 'Whitehall',
    color: PropertyColor.RED,
    rotation: CellRotation.RIGHT,
    position: {
      xStart: 11,
      yStart: 2,
      xEnd: 12,
      yEnd: 3,
    },
  },
  {
    type: CellType.PROPERTY,
    id: 8,
    price: 71,
    levelInfo: {
      level: 0,
      label: 'level',
      rent: [84, 101, 120, 141, 164],
    },
    title: 'Bow Street',
    color: PropertyColor.LIGHT_BLUE,
    rotation: CellRotation.LEFT,
    position: {
      xStart: 1,
      yStart: 3,
      xEnd: 2,
      yEnd: 4,
    },
  },
  {
    type: CellType.CHANCE,
    id: 22,
    color: PropertyColor.NONE,
    rotation: CellRotation.RIGHT,
    position: {
      xStart: 11,
      yStart: 3,
      xEnd: 12,
      yEnd: 4,
    },
  },
  {
    type: CellType.CHANCE,
    id: 7,
    color: PropertyColor.NONE,
    rotation: CellRotation.LEFT,
    position: {
      xStart: 1,
      yStart: 4,
      xEnd: 2,
      yEnd: 5,
    },
  },
  {
    type: CellType.PROPERTY,
    id: 23,
    price: 215,
    levelInfo: {
      level: 0,
      label: 'level',
      rent: [240, 270, 303, 338, 374],
    },
    title: 'Pentonville Road',
    color: PropertyColor.RED,
    rotation: CellRotation.RIGHT,
    position: {
      xStart: 11,
      yStart: 4,
      xEnd: 12,
      yEnd: 5,
    },
  },
  {
    type: CellType.PROPERTY,
    id: 6,
    price: 68,
    levelInfo: {
      level: 0,
      label: 'level',
      rent: [82, 99, 118, 139, 162],
    },
    title: 'Leicester Square',
    color: PropertyColor.LIGHT_BLUE,
    rotation: CellRotation.LEFT,
    position: {
      xStart: 1,
      yStart: 5,
      xEnd: 2,
      yEnd: 6,
    },
  },
  {
    type: CellType.PROPERTY,
    id: 24,
    price: 228,
    levelInfo: {
      level: 0,
      label: 'level',
      rent: [255, 285, 318, 354, 392],
    },
    title: 'Pall Mall',
    color: PropertyColor.RED,
    rotation: CellRotation.RIGHT,
    position: {
      xStart: 11,
      yStart: 5,
      xEnd: 12,
      yEnd: 6,
    },
  },
  {
    type: CellType.TRAIN_STATION,
    id: 5,
    price: 700,
    levelInfo: {
      level: 0,
      label: 'station',
      rent: [800, 1000, 1200, 1400],
    },
    title: 'Marylebone Station',
    color: PropertyColor.NONE,
    rotation: CellRotation.LEFT,
    position: {
      xStart: 1,
      yStart: 6,
      xEnd: 2,
      yEnd: 7,
    },
  },
  {
    type: CellType.TRAIN_STATION,
    id: 25,
    price: 700,
    levelInfo: {
      level: 0,
      label: 'station',
      rent: [800, 1000, 1200, 1400],
    },
    title: 'Kings Cross Station',
    color: PropertyColor.NONE,
    rotation: CellRotation.RIGHT,
    position: {
      xStart: 11,
      yStart: 6,
      xEnd: 12,
      yEnd: 7,
    },
  },
  {
    type: CellType.TAX_COLLECTOR,
    id: 4,
    price: 100,
    color: PropertyColor.NONE,
    rotation: CellRotation.LEFT,
    position: {
      xStart: 1,
      yStart: 7,
      xEnd: 2,
      yEnd: 8,
    },
  },
  {
    type: CellType.PROPERTY,
    id: 26,
    price: 271,
    levelInfo: {
      level: 0,
      label: 'level',
      rent: [300, 330, 363, 400, 440],
    },
    title: 'Bond Street',
    color: PropertyColor.YELLOW,
    rotation: CellRotation.RIGHT,
    position: {
      xStart: 11,
      yStart: 7,
      xEnd: 12,
      yEnd: 8,
    },
  },
  {
    type: CellType.PROPERTY,
    id: 3,
    price: 57,
    levelInfo: {
      level: 0,
      label: 'level',
      rent: [70, 85, 102, 121, 142],
    },
    title: 'Coventry Street',
    color: PropertyColor.BROWN,
    rotation: CellRotation.LEFT,
    position: {
      xStart: 1,
      yStart: 8,
      xEnd: 2,
      yEnd: 9,
    },
  },
  {
    type: CellType.PROPERTY,
    id: 27,
    price: 320,
    levelInfo: {
      level: 0,
      label: 'level',
      rent: [350, 390, 430, 475, 525],
    },
    title: 'Strand',
    color: PropertyColor.YELLOW,
    rotation: CellRotation.RIGHT,
    position: {
      xStart: 11,
      yStart: 8,
      xEnd: 12,
      yEnd: 9,
    },
  },
  {
    type: CellType.COMMUNITY_CHEST,
    id: 2,
    color: PropertyColor.NONE,
    rotation: CellRotation.LEFT,
    position: {
      xStart: 1,
      yStart: 9,
      xEnd: 2,
      yEnd: 10,
    },
  },
  {
    type: CellType.SPECIAL_PROPERTY,
    id: 28,
    price: 8000,
    levelInfo: {
      level: 0,
      label: 'level',
      rent: [10000, 12000, 14000, 16000, 18000],
    },
    specialType: SpecialType.LAMP,
    title: 'Whater Works',
    color: PropertyColor.NONE,
    rotation: CellRotation.RIGHT,
    position: {
      xStart: 11,
      yStart: 9,
      xEnd: 12,
      yEnd: 10,
    },
  },
  {
    type: CellType.PROPERTY,
    color: PropertyColor.BROWN,
    id: 1,
    price: 15,
    levelInfo: {
      level: 0,
      label: 'level',
      rent: [20, 30, 40, 50, 60],
    },
    title: 'Vine Street',
    rotation: CellRotation.LEFT,
    position: {
      xStart: 1,
      yStart: 10,
      xEnd: 2,
      yEnd: 11,
    },
  },
  {
    type: CellType.PROPERTY,
    id: 29,
    price: 370,
    levelInfo: {
      level: 0,
      label: 'level',
      rent: [400, 450, 500, 550, 600],
    },
    title: 'Regent Street',
    color: PropertyColor.YELLOW,
    rotation: CellRotation.RIGHT,
    position: {
      xStart: 11,
      yStart: 10,
      xEnd: 12,
      yEnd: 11,
    },
  },
  {
    type: CellType.START,
    id: 0,
    color: PropertyColor.NONE,
    rotation: CellRotation.DOWN,
    position: {
      xStart: 1,
      yStart: 11,
      xEnd: 2,
      yEnd: 12,
    },
  },
  {
    type: CellType.PROPERTY,
    id: 39,
    price: 1800,
    levelInfo: {
      level: 0,
      label: 'level',
      rent: [2000, 2500, 3000, 3500, 4000],
    },
    title: 'Mayfair',
    color: PropertyColor.DARK_BLUE,
    rotation: CellRotation.DOWN,
    position: {
      xStart: 2,
      yStart: 11,
      xEnd: 3,
      yEnd: 12,
    },
  },
  {
    type: CellType.TAX_COLLECTOR,
    id: 38,
    price: 200,
    color: PropertyColor.NONE,
    rotation: CellRotation.DOWN,
    position: {
      xStart: 3,
      yStart: 11,
      xEnd: 4,
      yEnd: 12,
    },
  },
  {
    type: CellType.PROPERTY,
    id: 37,
    levelInfo: {
      level: 0,
      label: 'level',
      rent: [582, 627, 675, 725, 778],
    },
    price: 562,
    title: 'Park Lane',
    color: PropertyColor.DARK_BLUE,
    rotation: CellRotation.DOWN,
    position: {
      xStart: 4,
      yStart: 11,
      xEnd: 5,
      yEnd: 12,
    },
  },
  {
    type: CellType.CHANCE,
    id: 36,
    color: PropertyColor.NONE,
    rotation: CellRotation.DOWN,
    position: {
      xStart: 5,
      yStart: 11,
      xEnd: 6,
      yEnd: 12,
    },
  },
  {
    type: CellType.TRAIN_STATION,
    id: 35,
    price: 700,
    levelInfo: {
      level: 0,
      label: 'station',
      rent: [800, 1000, 1200, 1400],
    },
    title: 'Liverpool Street Station',
    color: PropertyColor.NONE,
    rotation: CellRotation.DOWN,
    position: {
      xStart: 6,
      yStart: 11,
      xEnd: 7,
      yEnd: 12,
    },
  },
  {
    type: CellType.PROPERTY,
    id: 34,
    levelInfo: {
      level: 0,
      label: 'level',
      rent: [600, 700, 800, 900, 1000],
    },
    price: 550,
    title: 'Oxford Street',
    color: PropertyColor.GREEN,
    rotation: CellRotation.DOWN,
    position: {
      xStart: 7,
      yStart: 11,
      xEnd: 8,
      yEnd: 12,
    },
  },
  {
    type: CellType.COMMUNITY_CHEST,
    id: 33,
    color: PropertyColor.NONE,
    rotation: CellRotation.DOWN,
    position: {
      xStart: 8,
      yStart: 11,
      xEnd: 9,
      yEnd: 12,
    },
  },
  {
    type: CellType.PROPERTY,
    id: 32,
    price: 440,
    levelInfo: {
      level: 0,
      label: 'level',
      rent: [500, 550, 600, 650, 700],
    },
    title: 'Piccadilly',
    color: PropertyColor.GREEN,
    rotation: CellRotation.DOWN,
    position: {
      xStart: 9,
      yStart: 11,
      xEnd: 10,
      yEnd: 12,
    },
  },
  {
    type: CellType.PROPERTY,
    id: 31,
    price: 404,
    levelInfo: {
      level: 0,
      label: 'level',
      rent: [450, 500, 550, 600, 650],
    },
    title: 'Euston Road',
    color: PropertyColor.GREEN,
    rotation: CellRotation.DOWN,
    position: {
      xStart: 10,
      yStart: 11,
      xEnd: 11,
      yEnd: 12,
    },
  },
  {
    type: CellType.GO_TO_JAIL,
    id: 30,
    color: PropertyColor.NONE,
    rotation: CellRotation.DOWN,
    position: {
      xStart: 11,
      yStart: 11,
      xEnd: 12,
      yEnd: 12,
    },
  },
];
